services:
  news-bot:
    build: .
    # ENV가 production이면 naver-stock-news-bot, 아니면 naver-stock-news-bot-dev
    image: naver-stock-news-bot:${ENV:-dev}
    container_name: naver-stock-news-bot${ENV_SUFFIX:-}
    user: "1001:1001"
  # 잠시 주석 처리
    restart: always
    env_file: .env
    volumes:
      - ~/sqlite3:/app/db
      - ~/log:/app/log
