services:
  news-bot:
    image: ghcr.io/liante0904/naver-stock-news:latest
    container_name: naver-stock-news-bot
    user: "1001:1001"
    restart: always
    env_file: .env
    volumes:
      - ~/sqlite3:/app/db
      - ~/log:/app/log
